#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=8:30:00
#PBS -N mrtrix3_preproc
#PBS -V

module load singularity 2> /dev/null

## container version
tag=3.0_RC2

echo "Preprocessing data..."
time singularity exec -e docker://brainlife/mrtrix3:$tag ./mrtrix3_preproc.sh

if [ -s dwi*acpc*.nii.gz ]
then
    exit 0
else
    echo "Final AC-PC alinged dwi data missing."
    exit 1
fi

